"""Executive Summary PDF exporter (1 page).

Design goals:
- Stable, short, and audit-friendly
- Safe against missing fields
- No Streamlit dependency

This is intentionally concise; the Decision Report PDF carries the longform journal.
"""

from __future__ import annotations

from typing import Any, Dict, Optional


def _safe_str(x: Any) -> str:
    try:
        return "" if x is None else str(x)
    except Exception:
        return ""


def _pick(d: Any, keys: list[str], default: Any = None) -> Any:
    cur = d
    for k in keys:
        if not isinstance(cur, dict):
            return default
        cur = cur.get(k)
    return cur if cur is not None else default


def build_executive_summary_pdf_bytes(
    *,
    systems_artifact: Optional[Dict[str, Any]],
    point_artifact: Any = None,
    top_candidate: Optional[Dict[str, Any]] = None,
) -> bytes:
    """Return a one-page PDF summary as bytes."""

    # ReportLab is installed in the environment.
    from io import BytesIO
    from reportlab.lib.pagesizes import LETTER
    from reportlab.lib.units import inch
    from reportlab.pdfgen import canvas

    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=LETTER)
    w, h = LETTER

    # Header
    c.setFont("Helvetica-Bold", 14)
    c.drawString(0.75 * inch, h - 0.75 * inch, "SHAMS Systems Mode — Executive Summary")

    c.setFont("Helvetica", 9)
    y = h - 1.05 * inch

    art = systems_artifact or {}
    design_intent = _safe_str(art.get("design_intent") or "")
    schema_version = _safe_str(art.get("schema_version") or "1")
    inputs_hash = _safe_str(art.get("inputs_hash") or "")
    rid = _safe_str(art.get("rid") or art.get("run_id") or "")

    def line(label: str, value: str) -> None:
        nonlocal y
        c.setFont("Helvetica-Bold", 9)
        c.drawString(0.75 * inch, y, f"{label}:")
        c.setFont("Helvetica", 9)
        c.drawString(2.2 * inch, y, value[:110])
        y -= 0.18 * inch

    line("Design intent", design_intent)
    line("Schema version", schema_version)
    if rid:
        line("Run id", rid)
    if inputs_hash:
        line("Inputs hash", inputs_hash)

    # Key Systems outcomes (if present)
    y -= 0.08 * inch
    c.setFont("Helvetica-Bold", 11)
    c.drawString(0.75 * inch, y, "Key outcomes")
    y -= 0.22 * inch

    # Pull common outcomes from artifact
    ok = art.get("ok")
    reason = _safe_str(art.get("reason") or "")
    line("Systems ok", _safe_str(ok))
    if reason:
        line("Reason", reason)

    # Headline metrics (from point artifact if available)
    try:
        headline = {}
        if isinstance(point_artifact, dict):
            headline = point_artifact.get("headline") or {}
        if isinstance(headline, dict) and headline:
            y -= 0.08 * inch
            c.setFont("Helvetica-Bold", 11)
            c.drawString(0.75 * inch, y, "Point headline")
            y -= 0.22 * inch
            for k in ["Q_DT_eqv", "H98", "Pfus_MW", "Palpha_MW", "q95", "q_div"]:
                if k in headline:
                    line(k, _safe_str(headline.get(k)))
    except Exception:
        pass

    # Top candidate summary
    if isinstance(top_candidate, dict) and top_candidate:
        y -= 0.08 * inch
        c.setFont("Helvetica-Bold", 11)
        c.drawString(0.75 * inch, y, "Top candidate")
        y -= 0.22 * inch
        cid = _safe_str(top_candidate.get("inputs_hash") or top_candidate.get("hash") or "")
        if cid:
            line("Candidate id", cid)
        for k in ["score", "perf_score", "margin_score"]:
            if k in top_candidate:
                line(k, _safe_str(top_candidate.get(k)))
        fam = _safe_str(top_candidate.get("family") or top_candidate.get("family_key") or "")
        if fam:
            line("Family", fam)

    # Footer
    c.setFont("Helvetica", 8)
    c.drawString(0.75 * inch, 0.6 * inch, "Generated by SHAMS Systems Mode (0-D). Use Decision Report for full journal + trace.")

    c.showPage()
    c.save()
    return buf.getvalue()
