# SHAMS Requirements (editable)
# Each requirement maps to evidence in constraints and KPIs.
# Fields:
#  id: unique requirement id
#  text: plain-language requirement
#  constraints: list of constraint names (or prefixes) that demonstrate compliance
#  kpis: list of KPI keys (from decision/kpis.py) that provide supporting values
#  severity: must|should
requirements:
  - id: REQ-FEAS-01
    text: "All hard constraints must pass with non-negative margin."
    constraints: ["*"]   # '*' means all hard constraints
    kpis: ["feasible_hard", "min_hard_margin"]
    severity: must

  - id: REQ-DEC-01
    text: "Reference design must satisfy decision-grade conservative maturity unless explicitly waived."
    constraints: ["decision_grade_ok"]
    kpis: ["decision_grade_ok"]
    severity: must

  - id: REQ-ENG-01
    text: "Thermal power and net electric power must be reported."
    constraints: []
    kpis: ["P_fusion_MW", "P_e_net_MW"]
    severity: should
