"""Reactor Design Forge — Design Card (v1)

A one-page, reviewer-friendly card for a selected candidate. It is a compact
rendering of:
 - key truth outputs (selected)
 - closure (gross/recirc/net)
 - margins (tight constraints)
 - reality gates

No ranking. No recommendations.
"""

from __future__ import annotations

from typing import Any, Dict, List


def build_design_card_md(candidate: Dict[str, Any]) -> str:
    c = candidate or {}
    cid = str(c.get("id") or c.get("candidate_id") or "")
    feas = str(c.get("feasibility_state") or "")
    robust = str(c.get("robustness_class") or "")
    intent = str(c.get("design_intent") or c.get("intent") or "")

    inp = c.get("inputs") or {}
    outs = c.get("outputs") or {}
    closure = c.get("closure_bundle") or {}
    mb = c.get("margin_budget") or {}
    gates = c.get("reality_gates") or {}

    lines: List[str] = []
    lines.append(f"# Design Card — {cid or '(candidate)'}")
    if intent:
        lines.append(f"- Intent: **{intent}**")
    if feas:
        lines.append(f"- Feasibility: **{feas}** (robustness: **{robust or 'n/a'}**)")

    # Key inputs
    key_in = ["R0_m", "a_m", "kappa", "Bt_T", "Ip_MA", "fG"]
    present_in = [k for k in key_in if k in inp]
    if present_in:
        lines.append("\n## Key Inputs")
        for k in present_in:
            lines.append(f"- {k}: `{inp[k]}`")

    # Key outputs (best-effort)
    key_out = ["Q_DT_eqv", "H98", "q95", "P_fus_MW", "P_e_net_MW"]
    present_out = [k for k in key_out if k in outs]
    if present_out:
        lines.append("\n## Key Outputs (Truth)")
        for k in present_out:
            lines.append(f"- {k}: `{outs[k]}`")

    # Closure
    if closure:
        lines.append("\n## Electric Closure")
        lines.append(f"- Gross electric: `{closure.get('gross_electric_MW')}` MW")
        lines.append(f"- Recirc electric: `{closure.get('recirc_electric_MW')}` MW")
        lines.append(f"- Net electric: `{closure.get('net_electric_MW')}` MW")

    # Tight constraints
    if isinstance(mb.get("tight_constraints"), list) and mb.get("tight_constraints"):
        lines.append("\n## Tight Constraints")
        for t in mb.get("tight_constraints")[:10]:
            lines.append(f"- {t}")

    # Reality gates
    if isinstance(gates.get("results"), list) and gates.get("results"):
        lines.append("\n## Reality Gates")
        for g in gates.get("results")[:10]:
            lines.append(f"- {g.get('gate')}: **{g.get('status')}**")

    lines.append("\n---")
    lines.append("_Generated by SHAMS Reactor Design Forge (audit-clean; no automatic application)._ ")
    return "\n".join(lines)
