from __future__ import annotations
import argparse, json
from pathlib import Path
from typing import Dict, Any

def make_process_handoff(artifact: Dict[str, Any]) -> Dict[str, Any]:
    inp = artifact.get("inputs", {}) or {}
    out = artifact.get("outputs", {}) or {}
    rb = artifact.get("radial_build", {}) or {}
    return {
        "kind": "process_handoff",
        "source": {"tool": "SHAMS-FUSION-X", "version": artifact.get("version"), "timestamp": artifact.get("timestamp")},
        "geometry": {"R0": inp.get("R0"), "a": inp.get("a"), "radial_build_segments": rb.get("segments", [])},
        "targets": {"Q": out.get("Q")},
        "feasibility": {"feasible": rb.get("feasible", artifact.get("meta", {}).get("feasible", None)), "constraints": artifact.get("constraints", [])},
        "notes": "Generated by SHAMS v98 handoff. Use as downstream input to PROCESS-like optimizers.",
    }

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--artifact", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    art = json.loads(Path(args.artifact).read_text(encoding="utf-8"))
    Path(args.out).write_text(json.dumps(make_process_handoff(art), indent=2, sort_keys=True), encoding="utf-8")
    print("Wrote", args.out)
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
