"""SHAMS — UI Wiring Index Generator

Generates a deterministic, reviewer-safe wiring index for ui/app.py without
running Streamlit.

Hard-locked constraints:
- Read-only: no truth execution.
- Deterministic output for a given repo state.
- No external dependencies.

Author: © 2026 Afshin Arjhangmehr
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import hashlib


@dataclass(frozen=True)
class WiringHit:
    label: str
    pattern: str
    first_line_1idx: Optional[int]
    context: str


def _sha256_bytes(b: bytes) -> str:
    h = hashlib.sha256()
    h.update(b)
    return h.hexdigest()


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _find_first(lines: Sequence[str], needle: str) -> Optional[int]:
    for i, ln in enumerate(lines, start=1):
        if needle in ln:
            return i
    return None


def _context_window(lines: Sequence[str], line_1idx: Optional[int], radius: int = 2) -> str:
    if line_1idx is None:
        return ""
    i0 = max(1, line_1idx - radius)
    i1 = min(len(lines), line_1idx + radius)
    out = []
    for i in range(i0, i1 + 1):
        out.append(f"{i:>7}: {lines[i-1].rstrip()}")
    return "\n".join(out)


def build_ui_wiring_index_markdown(repo_root: Path) -> str:
    """Return a deterministic markdown wiring index for core UI modes."""
    app_py = repo_root / "ui" / "app.py"
    if not app_py.exists():
        raise FileNotFoundError(f"Missing ui/app.py at: {app_py}")

    raw = app_py.read_bytes()
    sha = _sha256_bytes(raw)
    text = raw.decode("utf-8", errors="replace")
    lines = text.splitlines()

    # Key anchors: tabs and the requested modes.
    hits: List[WiringHit] = []
    def add(label: str, pattern: str, needle: str) -> None:
        ln = _find_first(lines, needle)
        hits.append(WiringHit(label=label, pattern=pattern, first_line_1idx=ln, context=_context_window(lines, ln)))

    add("Tabs creation", "st.tabs([...])", "st.tabs([")
    add("Systems Mode tab block", "with tab_systems:", "with tab_systems")
    add("Scan Lab tab block", "with tab_scan:", "with tab_scan")
    add("Pareto Lab tab block", "with tab_pareto:", "with tab_pareto")
    add("Trade Study Studio import", "from ui.trade_study_studio import render_trade_study_studio", "render_trade_study_studio")
    add("External Optimization Workbench deck", 'External Optimization Workbench', "External Optimization Workbench")
    add("PROCESS parity benchmarks view", "view == 'PROCESS parity benchmarks'", "PROCESS parity benchmarks")
    add("Reviewer Packet view", "view == 'Reviewer Packet'", "Reviewer Packet")

    # Compose markdown
    md: List[str] = []
    md.append("# SHAMS UI Wiring Index (static)")
    md.append("")
    md.append("This artifact is generated by static inspection of `ui/app.py` (no Streamlit execution).")
    md.append("")
    md.append(f"- ui/app.py sha256: `{sha}`")
    md.append(f"- ui/app.py lines: `{len(lines)}`")
    md.append("")
    md.append("## Mode wiring anchors")
    md.append("")
    md.append("| Item | Pattern | First line (1-indexed) |")
    md.append("|---|---|---:|")
    for h in hits:
        ln = h.first_line_1idx if h.first_line_1idx is not None else ""
        md.append(f"| {h.label} | `{h.pattern}` | {ln} |")
    md.append("")
    md.append("## Context snippets")
    md.append("")
    for h in hits:
        md.append(f"### {h.label}")
        md.append("")
        if h.first_line_1idx is None:
            md.append("_Not found._")
        else:
            md.append("```")
            md.append(h.context)
            md.append("```")
        md.append("")
    return "\n".join(md)


def write_ui_wiring_index(repo_root: Path, out_path: Path) -> Path:
    """Write the wiring index markdown to out_path and return it."""
    md = build_ui_wiring_index_markdown(repo_root=repo_root)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(md, encoding="utf-8")
    return out_path
