"""Reactor Design Forge — Design Card (v1)

A one-page, reviewer-friendly card for a selected candidate. It is a compact
rendering of:
 - key truth outputs (selected)
 - closure (gross/recirc/net)
 - margins (tight constraints)
 - reality gates

No ranking. No recommendations.

PHYS-KPI-001: on INFEASIBLE candidates, claim FoMs (Q / H98 / Pfus / P_net)
are shown as diagnostic residue — never as design achievements.
"""

from __future__ import annotations

from typing import Any, Dict, List

_CLAIM_OUT_KEYS = frozenset(
    {
        "Q_DT_eqv",
        "Q",
        "H98",
        "P_fus_MW",
        "Pfus_MW",
        "Pfus_total_MW",
        "Pfus_DT_adj_MW",
        "P_e_net_MW",
        "P_net_e_MW",
        "Pe_net_MW",
    }
)
_DIAGNOSTIC = "— (diagnostic)"


def _candidate_feasible(c: Dict[str, Any]) -> bool:
    if "feasible" in c:
        return bool(c.get("feasible"))
    state = str(c.get("feasibility_state") or "").strip().upper()
    return state == "FEASIBLE"


def _fmt_claim(key: str, value: Any, *, feasible: bool) -> str:
    if (not feasible) and (str(key) in _CLAIM_OUT_KEYS or str(key) == "net_electric_MW"):
        return _DIAGNOSTIC
    return f"`{value}`"


def build_design_card_md(candidate: Dict[str, Any]) -> str:
    c = candidate or {}
    cid = str(c.get("id") or c.get("candidate_id") or "")
    feas = str(c.get("feasibility_state") or "")
    robust = str(c.get("robustness_class") or "")
    intent = str(c.get("design_intent") or c.get("intent") or "")
    feasible = _candidate_feasible(c)

    inp = c.get("inputs") or {}
    outs = c.get("outputs") or {}
    closure = c.get("closure_bundle") or {}
    mb = c.get("margin_budget") or {}
    gates = c.get("reality_gates") or {}

    lines: List[str] = []
    lines.append(f"# Design Card — {cid or '(candidate)'}")
    if intent:
        lines.append(f"- Intent: **{intent}**")
    if feas:
        lines.append(f"- Feasibility: **{feas}** (robustness: **{robust or 'n/a'}**)")
    elif "feasible" in c:
        lines.append(
            f"- Feasibility: **{'FEASIBLE' if feasible else 'INFEASIBLE'}** "
            f"(robustness: **{robust or 'n/a'}**)"
        )
    if not feasible:
        lines.append(
            "- PHYS-KPI-001: claim FoMs (Q / H98 / Pfus / P_net) below are "
            "**diagnostic residue** — not design claims."
        )

    # Key inputs
    key_in = ["R0_m", "a_m", "kappa", "Bt_T", "Ip_MA", "fG"]
    present_in = [k for k in key_in if k in inp]
    if present_in:
        lines.append("\n## Key Inputs")
        for k in present_in:
            lines.append(f"- {k}: `{inp[k]}`")

    # Key outputs (best-effort) — prefer L0 names; accept legacy aliases.
    key_out_aliases = (
        ("Q_DT_eqv", ("Q_DT_eqv", "Q")),
        ("H98", ("H98", "H_IPB98y2", "H98y2", "H_IPB98")),
        ("q95_proxy", ("q95_proxy", "q95")),
        ("Pfus_total_MW", ("Pfus_total_MW", "P_fus_MW", "Pfus_MW")),
        ("P_e_net_MW", ("P_e_net_MW", "P_net_e_MW", "Pe_net_MW", "P_net_MW")),
    )
    present_out: list[tuple[str, Any]] = []
    for label, aliases in key_out_aliases:
        for k in aliases:
            if k in outs and outs.get(k) is not None:
                present_out.append((label, outs.get(k)))
                break
    if present_out:
        heading = "Key Outputs (Truth)" if feasible else "Key Outputs (diagnostic on INFEASIBLE)"
        lines.append(f"\n## {heading}")
        for k, val in present_out:
            if (not feasible) and (k in _CLAIM_OUT_KEYS or k in ("Q_DT_eqv", "H98", "Pfus_total_MW", "P_e_net_MW", "P_fus_MW")):
                lines.append(f"- {k}: {_DIAGNOSTIC}")
            else:
                lines.append(f"- {k}: `{val}`")

    # Closure
    if closure:
        lines.append("\n## Electric Closure")
        lines.append(f"- Gross electric: `{closure.get('gross_electric_MW')}` MW")
        lines.append(f"- Recirc electric: `{closure.get('recirc_electric_MW')}` MW")
        net_disp = _fmt_claim("net_electric_MW", closure.get("net_electric_MW"), feasible=feasible)
        if feasible:
            lines.append(f"- Net electric: {net_disp} MW")
        else:
            lines.append(f"- Net electric: {net_disp} (not a design claim)")

    # Tight constraints
    if isinstance(mb.get("tight_constraints"), list) and mb.get("tight_constraints"):
        lines.append("\n## Tight Constraints")
        for t in mb.get("tight_constraints")[:10]:
            lines.append(f"- {t}")

    # Reality gates
    if isinstance(gates.get("results"), list) and gates.get("results"):
        lines.append("\n## Reality Gates")
        for g in gates.get("results")[:10]:
            lines.append(f"- {g.get('gate')}: **{g.get('status')}**")

    lines.append("\n---")
    lines.append("_Generated by SHAMS Reactor Design Forge (audit-clean; no automatic application)._ ")
    return "\n".join(lines)
