from __future__ import annotations

_RERUN_SCRIPT = '''#!/usr/bin/env python3
"""Re-run a SHAMS capsule (offline-friendly)."""
import json
from pathlib import Path

def main():
    here = Path(__file__).resolve().parent
    art = json.loads((here/'artifact.json').read_text(encoding='utf-8'))
    try:
        from tools.validate_schemas import _fallback_validate
        schema = json.loads((here/'..'/'..'/'schemas'/'shams_run_artifact.schema.json').read_text(encoding='utf-8'))
        errs = _fallback_validate(art, schema)
        print("Schema:", "PASS" if not errs else "FAIL")
        for e in errs[:20]:
            print(" -", e)
    except Exception:
        print("Schema: skipped")

    figdir = here/'figures'
    figdir.mkdir(exist_ok=True, parents=True)
    try:
        from src.shams_io.plotting import plot_radial_build_dual_export
        plot_radial_build_dual_export(art, str(figdir/'radial_build'))
        print("Figures exported.")
    except Exception as e:
        print("Figures skipped:", repr(e))
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
'''

"""
Reproducibility Capsule Export (v90)

Produces a self-contained capsule directory:
- manifest.json (hashes + version + constraint hash)
- inputs.json / outputs.json / constraints.json
- figures/*.png and *.svg (best-effort)
- README.md (how to cite / reproduce)

Additive only; does not change physics or solvers.
"""
import argparse, json, os, hashlib, time
from pathlib import Path
from typing import Any, Dict

def _sha256_bytes(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()

def _sha256_file(p: Path) -> str:
    return _sha256_bytes(p.read_bytes())

def export_capsule(artifact: Dict[str, Any], outdir: str) -> Dict[str, Any]:
    out = Path(outdir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "figures").mkdir(exist_ok=True)

    # Core exports
    (out / "artifact.json").write_text(json.dumps(artifact, indent=2, sort_keys=True), encoding="utf-8")

    inputs = artifact.get("inputs", {})
    outputs = artifact.get("outputs", {})
    constraints = artifact.get("constraints", [])

    (out / "inputs.json").write_text(json.dumps(inputs, indent=2, sort_keys=True), encoding="utf-8")
    (out / "outputs.json").write_text(json.dumps(outputs, indent=2, sort_keys=True), encoding="utf-8")
    (out / "constraints.json").write_text(json.dumps(constraints, indent=2, sort_keys=True), encoding="utf-8")

    # Figures (best-effort)
    try:
        from src.shams_io.plotting import plot_radial_build_from_artifact, plot_radial_build_dual_export
        base = out / "figures" / "radial_build"
        try:
            plot_radial_build_dual_export(artifact, str(base))
        except Exception:
            png_path = out / "figures" / "radial_build.png"
            plot_radial_build_from_artifact(artifact, str(png_path))
    except Exception:
        pass

    # SVG export (best-effort): if matplotlib figure is not returned by plotting fn, we just provide PNG.
    # Future: add explicit SVG-capable plotting calls.
    readme = f"""# SHAMS Reproducibility Capsule

This capsule was generated by SHAMS–FUSION-X v90.

## Contents
- `manifest.json` — provenance and hashes
- `inputs.json` — point inputs
- `outputs.json` — model outputs
- `constraints.json` — full constraint records
- `artifact.json` — full run artifact
- `figures/` — paper-ready figures (best-effort)

## How to cite
Cite the SHAMS version/date and include the `manifest.json` hashes in your methods appendix.

## Notes
- Feasibility truth is authoritative in SHAMS.
- Any sandbox ranking outputs are non-authoritative and must be accompanied by feasibility artifacts.
"""
    (out / "README.md").write_text(readme, encoding="utf-8")

    manifest = {
        "kind": "shams_reproducibility_capsule",
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "version": artifact.get("version", "unknown"),
        "constraint_set_hash": artifact.get("meta", {}).get("constraint_set_hash", None),
        "hashes": {
            "artifact.json": _sha256_file(out / "artifact.json"),
            "inputs.json": _sha256_file(out / "inputs.json"),
            "outputs.json": _sha256_file(out / "outputs.json"),
            "constraints.json": _sha256_file(out / "constraints.json"),
        }
    }
    # Figure hashes
    figs = {}
    for p in (out / "figures").glob("*"):
        if p.is_file():
            figs[str(p.name)] = _sha256_file(p)
    manifest["hashes"]["figures"] = figs

    (out / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")
    return manifest

def main():
    ap = argparse.ArgumentParser(description="Export a SHAMS reproducibility capsule from artifact.json")
    ap.add_argument("--artifact-json", required=True)
    ap.add_argument("--outdir", required=True)
    args = ap.parse_args()

    with open(args.artifact_json, "r", encoding="utf-8") as f:
        artifact = json.load(f)

    export_capsule(artifact, args.outdir)
    print(f"Wrote capsule: {args.outdir}")

if __name__ == "__main__":
    main()
